services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: valauto-api
    environment:
      MODEL_PATH: /mnt/SUML-main/models/autogluon_price_model
      SUML_ROOT: /mnt/SUML-main
      CORS_ORIGINS: "http://localhost:5173,https://localhost"
    ports:
      - "8000:8000"
    volumes:
      - ../SUML-main:/mnt/SUML-main:rw
    restart: unless-stopped

  node:
    container_name: valauto-node
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
      target: node
    volumes:
      - .:/app
      - /app/node_modules
      - shared-dist:/app/dist

  nginx:
    container_name: valauto-nginx
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
      target: nginx
    depends_on:
      - node
    ports:
      - "443:443"
    volumes:
      - shared-dist:/usr/share/nginx/html

volumes:
  shared-dist: